name = "Banjo-Tooie"
home = "https://discord.com/channels/731205301247803413/1135352499172286505"
default_url = "https://github.com/jjjj12212/Archipelago-BanjoTooie/releases/download/V{{version}}/banjo_tooie.apworld"

[versions]
"4.5.1" = {}
"4.10.1" = {}
"4.10.2" = {}
"4.11.1" = {}
"4.11.2" = {}
"4.11.4" = {}
