name = "Bomberman 64"
home = "https://discord.com/channels/731205301247803413/1326400868773400677"
default_url = "https://github.com/Happyhappyism/Archipelago/releases/download/bomb64_v{{version}}/bomberman_64.apworld"

[versions]
# They pushed a version on top of 0.1.3 2 months after...
"0.1.3+hotfix1" = { url = "https://github.com/Happyhappyism/Archipelago/releases/download/bomb64_v0.1.3/bomberman_64.apworld" }
