name = "Candy Box 2"
home = "https://discord.com/channels/731205301247803413/1351112920398037015/"

[versions]
"0.1.0+20251208-1" = { url = "https://github.com/vicr123/Archipelago/releases/download/20251208-1/candybox2.apworld" }
