name = "Cave Story"
home = "https://discord.com/channels/731205301247803413/1083474864150695956"
default_url = "https://github.com/kl3cks7r/CaveStoryArchipelago/releases/download/{{version}}/cave_story.apworld"
# Disabled for causing issues with priority locations
# AssertionError: At the start of distribute_items_restrictive, there are items in the multiworld itempool that are already placed on locations:
# [(Labyrinth B - Booster Chest, Progressive Polar Star)]
disabled = true

[versions]
"0.6.5" = {}
