name = "Castlevania: Dawn of Sorrow"
home = "https://discord.com/channels/731205301247803413/1441671319690412052"

[versions]
"1.3.0" = { url = "https://github.com/PinkSwitch/Archipelago/releases/download/cvdos1.3/cv_dos.apworld" }
