default_url = "https://github.com/BuffYoda21/ap-glyphs/releases/download/v{{version}}/glyphs.apworld"
home = "https://discord.com/channels/731205301247803413/1401434680808575017"
name = "GLYPHS"

[versions]
"1.0.0" = {}
