name = "Manual_Borderlands4_jkxWinG"
display_name = "Manual: Borderlands 4"
tags = ["ad"]
disabled = true # Triggers some assertion, needs a manual update

[versions]
"0.1.4" = { url = "https://github.com/jkxWinG/Borderlands-4-Manual-AP/releases/download/Version0.1.4/manual_borderlands4_jkxwing.apworld" }
