name = "Manual_HonkaiStarRailGoldAndGears_Erkigmo"
display_name = "Manual: Gold And Gears"
home = "https://discord.com/channels/1097532591650910289/1448413373590147293"
default_url = "https://github.com/Erkigmo/Gold-And-Gears-Manual/releases/download/v{{version}}/manual_honkaistarrailgoldandgears_erkigmo.apworld"

[versions]
"0.1.2" = {}
