name = "Manual_EoWEchoHunt_killedragon"
display_name = "Manual: The Legend of Zelda - Echoes of Wisdom"
home = "https://discord.com/channels/1097532591650910289/1290033190961938452"

[versions]
"0.0.1" = { local = "../apworlds/manual_eowechohunt_killedragon-0.0.1.apworld" }
"0.0.2" = { local = "../apworlds/manual_eowechohunt_killedragon-0.0.2.apworld" }
