name = "Manual_ShovelKnightTreasureTrove_QLilaOfTorment"
display_name = "Manual: Shovel Knight - Specter of Torment"
home = "https://discord.com/channels/1097532591650910289/1363411568104312912"

[versions]
"0.0.1" = { local = "../apworlds/manual_shovelknighttreasuretrove_qlilaoftorment-0.0.1.apworld" }
