name = "Manual_CurrencyWars_MayaXTG"
display_name = "Manual: Honkai Star Rail: Currency Wars"
home = "https://discord.com/channels/1097532591650910289/1449553615373992148"

[versions]
"1.0.1" = { local = "../apworlds/manual_currencywars_mayaxtg-1.0.1.apworld" }
