name = "Manual_CartoonNetworkPunchTimeExplosionXL_BunkBunker"
display_name = "Manual: Cartoon Network Punch Time Explosion XL"
home = "https://discord.com/channels/1097532591650910289/1445597085897326632"
disabled = true # Triggers some assertion, needs a manual update

[versions]
"0.0.3" = { local = "../apworlds/manual_cartoonnetworkpunchtimeexplosionxl_bunkbunker-0.0.3.apworld" }
