name = "Manual_Touhou Fumo Racing_AwesomeZuils"
display_name = "Manual: Touhou Fumo Racing"
home = "https://discord.com/channels/1097532591650910289/1462399064627744819/1462513817547440252"

[versions]
"1.0.1" = {url = "https://github.com/zuils/AP-Manuals/releases/download/V4.0.1/manual_touhoufumoracing_awesomezuils.apworld" }
