name = "Manual_PlaytimewithPercy_WolfBoi008"
display_name = "Manual: Playtime with Percy"
home = "https://discord.com/channels/1097532591650910289/1422262889942876170"
default_url = "https://github.com/WolfBoi008/Playtime-with-Percy/releases/download/{{version}}/manual_playtimewithpercy_wolfboi008.apworld"

[versions]
"1.2.1" = {}
