name = "Manual_PlantsVsZombies2Gardendless_Trikehard"
display_name = "Manual: Plants Vs Zombies 2"
home = "https://discord.com/channels/1097532591650910289/1435957999809335368"
disabled = true # The apworld basically has 0 logic which I missed in review

[versions]
# https://discord.com/channels/1097532591650910289/1435957999809335368
"0.0.1" = { local = "../apworlds/manual_plantsvszombies2gardendless_trikehard-0.0.1.apworld" }
