display_name = "Manual: Monster Hunter Rise (Hub Quests)"
name = "Manual_MHRiseHub_Axxroy"
home = "https://discord.com/channels/1097532591650910289/1172769920610738246"

[versions]
"2.0.1+repacked2" = { local = "../apworlds/manual_mhrisehub_axxroy-2.0.1+repacked2.apworld" }
