name = "Manual_ISPYSpookyMansionWiiNormal_MJB20077"
display_name = "Manual: ISPY Spooky Mansion"
home = "https://discord.com/channels/1097532591650910289/1434302459966394459"

[versions]
"0.0.1" = { local = "../apworlds/manual_ispyspookymansionwiinormal_mjb20077-0.0.1.apworld" }
"0.0.2" = { local = "../apworlds/manual_ispyspookymansionwiinormal_mjb20077-0.0.2.apworld" }
