name  = "Hatsune Miku Project Diva Mega Mix+"
home = "https://discord.com/channels/731205301247803413/1241134454391443580"
default_url = "https://github.com/Cynichill/DivaAPworld/releases/download/{{version}}B/megamix.apworld"

[versions]
"1.4.0" = {}
"1.4.1-unofficial" = { url = "https://github.com/RePod/DivaAPworld-R/releases/download/1.4.1-R_251213-92bea83/megamix.apworld" }
"1.4.3" = {}
