name = "Scooby-Doo! Night of 100 Frights"
home = "https://discord.com/channels/731205301247803413/1188152412498829352"

[versions]
"1.3.5" = { url = "https://github.com/vgm5/Night_Of_100_Frights_ap_world/releases/download/Release_1_3_5/no100f.apworld" }
