name = "Pokemon Crystal"
home = "https://discord.com/channels/731205301247803413/1365127145709502575"
default_url = "https://github.com/gerbiljames/Archipelago/releases/download/{{version}}/pokemon_crystal.apworld"

[versions]
"4.0.12" = {}
"5.0.3" = {}
"5.1.6" = {}
"5.2.7" = {}
"5.3.0" = {}
"5.3.1" = {}
"5.3.2" = {}
"5.3.3" = {}
"5.3.5" = {}
