name = "Slime Rancher"
home = "https://discord.com/channels/731205301247803413/1108426937409486909"
default_url = "https://github.com/SWCreeperKing/Slimipelago/releases/download/v{{version}}/slime_rancher.apworld"

[versions]
"0.2.2" = {}