name = "Sonic Heroes"
home = "https://discord.com/channels/731205301247803413/1234592520403423352"
default_url = "https://github.com/Ethicallogic-Archipelago/SonicHeroesArchipelago/releases/download/{{version}}/sonic_heroes.apworld"

[versions]
"1.4.0" = {}
"1.5.0" = {}
"2.0.0" = {}
# Apworld was removed by mistake and reuploaded with a different checksum
"2.0.1+hotfix1" = { url = "https://github.com/Ethicallogic-Archipelago/SonicHeroesArchipelago/releases/download/2.0.1/sonic_heroes.apworld" }
