name = "Zork Grand Inquisitor"
home = "https://discord.com/channels/731205301247803413/1224389493289648218"
default_url = "https://github.com/SerpentAI/Archipelago/releases/download/zgi-v{{version}}/zork_grand_inquisitor.apworld"

[versions]
"2.0.6" = {}
