[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_MarioParty9_SmashEBrada', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=1.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_MarioParty9_SmashEBrada', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=1.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_MarioParty9_SmashEBrada', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=1.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_MarioParty9_SmashEBrada', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=1.0.1"
