[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_RobloxTowerDefenseSimulator_JuJubeanYT', option='filler_traps')"]]
__expected__ = "error"
__version__ = ">=1.0.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_RobloxTowerDefenseSimulator_JuJubeanYT', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=1.0.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_RobloxTowerDefenseSimulator_JuJubeanYT', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=1.0.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_RobloxTowerDefenseSimulator_JuJubeanYT', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=1.0.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_RobloxTowerDefenseSimulator_JuJubeanYT', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=1.0.0"
