[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_FireEmblemPathofRadiance_MercenaryGreil', option='goal')"]]
__expected__ = "error"
__version__ = ">=1.1.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_FireEmblemPathofRadiance_MercenaryGreil', option='filler_traps')"]]
__expected__ = "error"
__version__ = ">=1.1.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_FireEmblemPathofRadiance_MercenaryGreil', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=1.1.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_FireEmblemPathofRadiance_MercenaryGreil', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=1.1.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_FireEmblemPathofRadiance_MercenaryGreil', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=1.1.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_FireEmblemPathofRadiance_MercenaryGreil', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=1.1.0"
