[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_Fifa98RoadtotheWorldCup_Satanos', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=1.3.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_Fifa98RoadtotheWorldCup_Satanos', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=1.3.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_Fifa98RoadtotheWorldCup_Satanos', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=1.3.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_Fifa98RoadtotheWorldCup_Satanos', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=1.3.0"
