[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_OneMoreNight_WolfBoi008', option='goal')"]]
__expected__ = "error"
__version__ = ">=1.3.2"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_OneMoreNight_WolfBoi008', option='colored_fish')"]]
__expected__ = "error"
__version__ = ">=1.3.2"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_OneMoreNight_WolfBoi008', option='character_fish')"]]
__expected__ = "error"
__version__ = ">=1.3.2"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_OneMoreNight_WolfBoi008', option='rare_fish')"]]
__expected__ = "error"
__version__ = ">=1.3.2"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_OneMoreNight_WolfBoi008', option='placeholder')"]]
__expected__ = "error"
__version__ = ">=2.2.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_OneMoreNight_WolfBoi008', option='fragments')"]]
__expected__ = "error"
__version__ = ">=2.2.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_OneMoreNight_WolfBoi008', option='coop')"]]
__expected__ = "error"
__version__ = ">=2.2.0"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_OneMoreNight_WolfBoi008', option='fishsanity_achievements')"]]
__expected__ = "error"
__version__ = ">=2.2.0"
