[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_GuitarHeroSmashHits_Smalls')"]]
__expected__ = "fail"
__version__ = ">=1.0.1"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_GuitarHeroSmashHits_Smalls')"]]
__expected__ = "fail"
__version__ = ">=1.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_GuitarHeroSmashHits_Smalls', option='include_tier_fcs')"]]
__expected__ = "error"
__version__ = ">=1.0.1"
