[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_DemonSlayerKimetsunoYaibaTheHinokamiChronicles_Inuzuka28')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_DemonSlayerKimetsunoYaibaTheHinokamiChronicles_Inuzuka28')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_DemonSlayerKimetsunoYaibaTheHinokamiChronicles_Inuzuka28', option='zenitsu_ic_dlc')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
