[["test.general.test_options.TestOptions.test_options_have_doc_string (game='Manual_HonkaiStarRailGoldAndGears_Erkigmo', option='starting_domains')"]]
__expected__ = "fail"
__version__ = ">=0.1.2"

[["test.general.test_options.TestOptions.test_options_have_doc_string (game='Manual_HonkaiStarRailGoldAndGears_Erkigmo', option='domain_type_checks')"]]
__expected__ = "fail"
__version__ = ">=0.1.2"

[["test.general.test_options.TestOptions.test_options_have_doc_string (game='Manual_HonkaiStarRailGoldAndGears_Erkigmo', option='shop_type_checks')"]]
__expected__ = "fail"
__version__ = ">=0.1.2"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_HonkaiStarRailGoldAndGears_Erkigmo', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=0.1.2"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_HonkaiStarRailGoldAndGears_Erkigmo', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=0.1.2"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_HonkaiStarRailGoldAndGears_Erkigmo', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=0.1.2"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_HonkaiStarRailGoldAndGears_Erkigmo', option='HasSecrets')"]]
__expected__ = "error"
__version__ = ">=0.1.2"
