[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_GrensEpicCartRideRobloxCreateACart_Grenhunterr', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_GrensEpicCartRideRobloxCreateACart_Grenhunterr', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_GrensEpicCartRideRobloxCreateACart_Grenhunterr', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_GrensEpicCartRideRobloxCreateACart_Grenhunterr', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
