[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_PlantsVsZombies2Gardendless_Trikehard', option='goal')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_PlantsVsZombies2Gardendless_Trikehard', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_PlantsVsZombies2Gardendless_Trikehard', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_PlantsVsZombies2Gardendless_Trikehard', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_PlantsVsZombies2Gardendless_Trikehard', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
